### ISSUE TITLE
Module is not compatible with just released PrestaShop 8.0.0

### ISSUE THREAD

**Issue by DrywFiltiarn** [buckaroo-it/PrestaShop#25]
A little over a week ago the new PrestaShop major release 8.0.0 was released. The current Buckaroo plugin does not install due to incompatibility with this new release.

As I'm about to venture on rebuilding an existing webshop with former Sisow payments to a new PrestaShop it would be great if the payment plugin for Buckaroo could be updated soon to be compatible with the new and future PrestaShop versions.

**Comment by Buckaroo-Rens** [comment]
Hi @DrywFiltiarn we are indeed aware of the new PrestaShop version (8.0) but there are still a lot of issues with it. Due to that we are not planning to fix support for it within the coming period. We will be first waiting for a more stable version of it (8.1). Also, it's a big release, a lot of thinks/logic has changed, so it will take a while for we will even be able to support it.

Beside the support we are planning on doing a complete cleanup/refactor of our plugin. Better code, more functionality, more supported payment methods.

**Comment by tajriba** [comment]
Hi, prestashop 803 is stable enough.

**Comment by Buckaroo-Rens** [comment]
@tajriba Correct, and as you might have seen in our branches we are working on it ;) But we are doing more then only support. We are working on a big refactor of the whole module, this is why it's taking longer (then expected).

**Comment by MatjeGit** [comment]
Hello Buckaroo-Rens,
Is there any perspective on how long it will take to the release of the version for Prestashop 8.1?

**Comment by venditdevs** [comment]
> Hello Buckaroo-Rens,
> Is there any perspective on how long it will take to the release of the version for Prestashop

Probably when Prestashop 9 is released.

The development disadvantage of Buckaroo/Sisow made it a lot easier to transfer all our customers with an Buckaroo/Sisow integration to another paymentprovider.

**Comment by MatjeGit** [comment]
Yes, we also left Buckaroo. So it does not matter anymore.

**Comment by Buckaroo-Rens** [comment]
@venditdevs @MatjeGit 

First of all, you are absolutely right that it takes a very long time. Unfortunately, the development process took longer than expected and we are currently in the testing phase before we make a new release. This plugin was first developed by third parties, so it took a lot of time to become familiar with it.

This release will be our biggest ever, PrestaShop has again risen high on our roadmap and we have spent many hours on improvements to the platform because we see the potential of the changes. Many new payment methods become available, new functions, the front and backend UI have been optimized. and so much more. The entire technology has also been improved and better aligned with PrestaShop standards.

However, we will really need a few more weeks before a full-fledged release follows.

**Comment by Buckaroo-Rens** [comment]
Release is done last week (4.0.0). 
https://github.com/buckaroo-it/PrestaShop/releases/tag/4.0.1 

Thanks for all the patience and sorry that it took so long @DrywFiltiarn, @tajriba, @MatjeGit & @venditdevs
